#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 1
#$ -l gpu,ngpu=1,gpu_arch=L40S
#$ -cwd
#$ -j y
#$ -N train-qwen
#$ -o train.log
#$ -m bea
#$ -M mattinglyw@si.edu
#
# ----------------Modules------------------------- #
#
export PATH=/home/mattinglyw/mambaforge/envs/ushmm/bin:$PATH
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
module load nvidia
# Run the Python script with the appropriate parameters
llamafactory-cli train \
    --stage sft \
    --do_train true \
    --model_name_or_path Qwen/Qwen2-VL-7B-Instruct \
    --preprocessing_num_workers 16 \
    --finetuning_type full \
    --template qwen2_vl \
    --dataset mllm_demo \
    --cutoff_len 1024 \
    --learning_rate 1.0e-4 \
    --num_train_epochs 3.0 \
    --max_samples 1000 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 500 \
    --warmup_ratio 0.1 \
    --output_dir /scratch/genomics/mattinglyw/saves/Qwen2VL-2B-Chat/lora/train_2024-09-04-13-53-27 \
    --bf16 true \
    --plot_loss true \
    --ddp_timeout 180000000 \
    --eval_steps 500 \
    --per_device_eval_batch_size 1 \
    --overwrite_output_dir true \
    --overwrite_cache true \
    --deepspeed examples/deepspeed/ds_z3_config.json

# /scratch/genomics/mattinglyw/saves/Qwen2VL-2B-Chat/lora/train_2024-09-04-13-53-27

echo = `date` job $JOB_NAME done